version: '3.8'
services:
  jenkins-docker:
        image: docker:18.09-dind
        restart: always
        privileged: true
        ports:
             - 2375:2375
        container_name: jenkins-docker
        volumes:
            - /opt/jenkins_home:/var/jenkins_home
        networks: 
            devops:
                aliases:
                    - docker
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    depends_on:
      - jenkins-docker
    volumes:
      - /opt/jenkins_home:/var/jenkins_home/
    ports:
      - "8280:8080"
    environment:
            - DOCKER_HOST=tcp://docker:2375
    networks:
      devops:
        aliases:
          - jenkins
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlab-ce
    hostname: '$GITLAB_HOSTNAME'
    ports:
      - "443:443"
      - "80:80"
      - "20:20"
    volumes:
      - /opt/gitlab/config:/etc/gitlab:Z
      - /opt/gitlab/logs:/var/log/gitlab:Z
      - /opt/gitlab/data:/var/opt/gitlab:Z
    networks:
      devops:
        aliases:
          - gitlab
  client:
    image: vncserver/lubuntu
    restart: always
    ports:
      - "5901:5901"
    container_name: client
    networks:
      devops:
        aliases:
          - client
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    depends_on: 
      - gitlab-ce
    container_name: gitlab-runner
    volumes:
      -  /opt/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      devops:
        aliases:
          - gitlab-runner

networks:
  devops:
