version: '3.8'
services:
  jenkins:
    build:
      context: jenkins/
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    restart: always
    privileged: true
    volumes:
      - /opt/jenkins_home/:/var/jenkins_home/
    ports:
      - "8280:8080"
    networks:
      devops:
        aliases:
          - jenkins
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlab-ce
    ports:
      - "443:443"
      - "80:80"
      - "20:20"
    volumes:
      - /opt/gitlab/config:/etc/gitlab:Z
      - /opt/gitlab/logs:/var/log/gitlab:Z
      - /opt/gitlab/data:/var/opt/gitlab:Z
networks:
  devops:
