version: '3.8'
services:
  jenkins-alpine:
    image: jenkins/jenkins:alpine
    volumes:
      - $PWD/jenkins_home/:/var/jenkins_home/
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      devops:
        aliases:
          - jenkins
networks:
  devops:
